export const events = [
    {
        title: 'Event 1',
        description: 'Description for Event 1',
        date: '31-0-2023',
        time: '1:00 Pm Starts',
        imageUrl: '../images/event.jpeg',
        link: 'event-1-link',
    },
    {
        title: 'Event 2',
        description: 'Description for Event 2',
        date: '31-0-2023',
        time: '1:00 Pm Starts',
        imageUrl: '../images/event.jpeg',
        link: 'event-2-link',
    },
    {
        title: 'Event 3',
        description: 'Description for Event 3',
        date: '31-0-2023',
        time: '1:00 Pm Starts',
        imageUrl: '../images/event.jpeg',
        link: 'event-3-link',
    },
    {
        title: 'Event 4',
        description: 'Description for Event 4',
        date: '31-0-2023',
        time: '1:00 Pm Starts',
        imageUrl: '../images/event.jpeg',
        link: 'event-4-link',
    },
    {
        title: 'Event 5',
        description: 'Description for Event 5',
        date: '31-0-2023',
        time: '1:00 Pm Starts',
        imageUrl: '../images/event1.jpeg',
        link: 'event-5-link',
    },
    {
        title: 'Event 6',
        description: 'Description for Event 6',
        date: '31-0-2023',
        time: '1:00 Pm Starts',
        imageUrl: '../images/event1.jpeg',
        link: 'event-6-link',
    },
    {
        title: 'Event 7',
        description: 'Description for Event 7',
        date: '31-0-2023',
        time: '1:00 Pm Starts',
        imageUrl: '../images/event1.jpeg',
        link: 'event-7-link',
    },
    {
        title: 'Event 8',
        description: 'Description for Event 8',
        date: '31-0-2023',
        time: '1:00 Pm Starts',
        imageUrl: '../images/event1.jpeg',
        link: 'event-8-link',
    },
];